version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "KinesisToS3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-co23e0doftav"
s3_prefix = "KinesisToS3"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
